version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "nodejs_app" # Edit here
          ContainerPort: 8080
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-05e6e358bfcce6868", "subnet-08bec4aaec4e77526"] # Edit here
            SecurityGroups: ["sg-06363646d6eece2d9"]  # Edit here
            AssignPublicIp: "DISABLED"
